# Generated by Django 4.1.7 on 2023-04-10 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_orderitems_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='cart.orderitems'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='first_name',
            field=models.ForeignKey(default='NAME', on_delete=django.db.models.deletion.CASCADE, to='cart.order'),
        ),
    ]
