# Generated by Django 4.1.7 on 2023-04-10 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_order_items_alter_orderitems_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='product_name',
            field=models.ForeignKey(default='product', on_delete=django.db.models.deletion.CASCADE, to='cart.order'),
        ),
    ]
