# Generated by Django 4.1.7 on 2023-04-10 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_productsize_size'),
        ('cart', '0005_alter_orderitems_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='product_name',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitems',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.products'),
        ),
    ]
