# Generated by Django 4.1.7 on 2023-04-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_remove_orderitems_total_price_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='total_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
