# Generated by Django 4.1.7 on 2023-04-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_remove_order_total_price_orderitems_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='size',
            field=models.CharField(default='S', max_length=10),
        ),
    ]
