# Generated by Django 4.1.7 on 2023-03-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='size',
            field=models.CharField(choices=[('Small', 'S'), ('Medium', 'M'), ('Large', 'L')], default='Small', max_length=25),
        ),
    ]
