# Generated by Django 4.1.7 on 2023-02-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_producttype_delete_testmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default='images/No-Image-Placeholder.svg.png', upload_to='images'),
        ),
    ]
