# Generated by Django 4.1.7 on 2023-03-30 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_producttype_options_alter_productsize_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(choices=[('Small', 'S'), ('Medium', 'M'), ('Large', 'L')], default='Small', max_length=25),
        ),
    ]
