# Generated by Django 4.1.7 on 2023-02-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default='No-Image-Placeholder.svg.png', upload_to='media/photos'),
        ),
    ]
