# Generated by Django 4.1.7 on 2023-03-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='item_slug',
            field=models.SlugField(default='item-slug'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
