# Generated by Django 4.1.7 on 2023-04-02 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productsize_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsize',
            options={'ordering': [models.Case(models.When(size='S', then=0), models.When(size='M', then=1), models.When(size='L', then=2), models.When(size='US 5', then=3), models.When(size='US 6', then=4), models.When(size='US 7', then=5), default=6, output_field=models.IntegerField())]},
        ),
        migrations.AddField(
            model_name='products',
            name='is_shoes',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('US 5', 'US 5'), ('US 6', 'US 6'), ('US 7', 'US 7')], default='S', max_length=25),
        ),
    ]
