# Generated by Django 4.1.7 on 2023-03-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_products_item_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='item_slug',
            field=models.SlugField(max_length=255),
        ),
    ]
