# Generated by Django 4.1.7 on 2023-04-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_productsize_options_products_is_shoes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsize',
            options={'ordering': [models.Case(models.When(size='S', then=0), models.When(size='M', then=1), models.When(size='L', then=2), default=5, output_field=models.IntegerField())]},
        ),
        migrations.RemoveField(
            model_name='products',
            name='is_shoes',
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(choices=[('', 'No sizes available'), ('S', 'S'), ('M', 'M'), ('L', 'L')], default='S', max_length=25),
        ),
    ]
