# Generated by Django 4.1.7 on 2023-03-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_products_item_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='item_slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
