# Generated by Django 4.1.7 on 2023-04-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productsize_options_remove_products_is_shoes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='item_slug',
            field=models.SlugField(max_length=255),
        ),
    ]
